org: scraperapi
app: scraper-api
service: crawler
useDotenv: true

plugins:
  - serverless-offline
  # - serverless-plugin-typescript
  # - serverless-webpack
  # - serverless-prisma-webpack

# custom:
#   webpack:
#     packager: npm
#     includeModules: true

provider:
  timeout: 29
  name: aws
  runtime: nodejs16.x
  environment:
    JWT_SECRET: ${param:JWT_SECRET, env:JWT_SECRET, 'secret'}
    JWT_REFRESH_SECRET: ${param:JWT_REFRESH_SECRET, env:JWT_REFRESH_SECRET, 'refreshSecret'}
    DATABASE_URL: ${param:DATABASE_URL, env:DATABASE_URL, 'mysql://root@127.0.0.1:3309/scraper-api'}

layers:
  PrismaClient:
    path: layers/prisma-client
  NodeModules:
    path: layers/node-modules
  Libs:
    path: layers/libs
  
package:
  individually: true

functions:
  info:
    handler: info.handler
    layers:
      - !Ref NodeModulesLambdaLayer
      - !Ref PrismaClientLambdaLayer
      - !Ref LibsLambdaLayer
    events:
      - httpApi:
          path: /info
          method: get
      
  createSitemap: 
    handler: sitemap.create
    events:
      - httpApi:
          path: /sitemaps
          method: post
    layers:
      - !Ref NodeModulesLambdaLayer
      - !Ref PrismaClientLambdaLayer
      - !Ref LibsLambdaLayer

  getSitemaps: 
    handler: sitemap.findAll
    layers:
      - !Ref NodeModulesLambdaLayer
      - !Ref LibsLambdaLayer
      - !Ref PrismaClientLambdaLayer
    events:
      - httpApi:
          path: /sitemaps
          method: get    

  getSitemapById: 
    handler: sitemap.findById
    events:
      - httpApi:
          path: /sitemaps/{id}
          method: get
    layers:
      - !Ref NodeModulesLambdaLayer
      - !Ref PrismaClientLambdaLayer
      - !Ref LibsLambdaLayer

  getSitemapResults:
    handler: sitemap.getSitemapResults
    events:
      - httpApi:
          path: /sitemaps/{id}/results
          method: get
    layers:
    - !Ref NodeModulesLambdaLayer
    - !Ref PrismaClientLambdaLayer
    - !Ref LibsLambdaLayer    

  getSitemapStatus:
    handler: sitemap.getSitemapStatus
    events:
      - httpApi:
          path: /sitemaps/{id}/status
          method: get
    layers:
      - !Ref NodeModulesLambdaLayer
      - !Ref PrismaClientLambdaLayer
      - !Ref LibsLambdaLayer

  updateOrCreateSelector:
    handler: selector.updateOrCreate
    events:
      - httpApi:
          path: /sitemaps/{id}/selectors
          method: put
    layers:
      - !Ref NodeModulesLambdaLayer
      - !Ref PrismaClientLambdaLayer
      - !Ref LibsLambdaLayer
  
  sitemapRoutine:
    timeout: 900
    memorySize: 900
    handler: sitemap-routine.handler
    tags:
      timing: onceByHour
    layers:
      - !Ref NodeModulesLambdaLayer
      - !Ref PrismaClientLambdaLayer
      - !Ref LibsLambdaLayer
    # events:
    #   - schedule: cron(0/5 * ? * * *) # every 5 minutes
      # - schedule: cron(0/5 * ? * * *) # every 5 minutes