name: 'Daily artifact cleanup'
on:
  schedule:
    - cron: '0/5 * * * *' # every 5 minutes
    # - cron: '0 1 * * *' # every night at 1 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: $
          expire-in: 0
          # expire-in: 7days # Set this to 0 to delete all artifacts